# Generated by Django 5.2.7 on 2025-10-30 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_completed_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_username', models.CharField(blank=True, max_length=255, null=True)),
                ('pseudo', models.CharField(blank=True, max_length=255, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('langues', models.JSONField(blank=True, default=list)),
                ('centres_interet', models.JSONField(blank=True, default=list)),
                ('type_contenu', models.JSONField(blank=True, default=list)),
                ('disponibilite_collaboration', models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé'), ('partiellement_disponible', 'Partiellement disponible')], default='disponible', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_categories', models.ManyToManyField(blank=True, related_name='influencers_categories', to='category.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Influencer',
                'verbose_name_plural': 'Influencers',
                'db_table': 'influencers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_marque', models.CharField(max_length=255)),
                ('campagne', models.CharField(max_length=255)),
                ('periode', models.CharField(max_length=100)),
                ('resultats', models.TextField(blank=True, null=True)),
                ('lien_publication', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='users.influencer')),
            ],
            options={
                'verbose_name': 'Collaboration',
                'verbose_name_plural': 'Collaborations',
                'db_table': 'collaborations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OffreCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_collaboration', models.CharField(choices=[('placement_produit', 'Placement produit'), ('story', 'Story'), ('post', 'Post'), ('video', 'Vidéo'), ('reel', 'Reel'), ('live', 'Live'), ('ambassadeur', 'Ambassadeur')], max_length=100)),
                ('tarif_minimum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_maximum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres_collaboration', to='users.influencer')),
            ],
            options={
                'verbose_name': 'Offre de Collaboration',
                'verbose_name_plural': 'Offres de Collaboration',
                'db_table': 'offres_collaboration',
                'ordering': ['type_collaboration'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_media', to='users.influencer')),
            ],
            options={
                'verbose_name': 'Portfolio Media',
                'verbose_name_plural': 'Portfolio Media',
                'db_table': 'portfolio_media',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ReseauSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateforme', models.CharField(choices=[('Instagram', 'Instagram'), ('TikTok', 'TikTok'), ('YouTube', 'YouTube'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('LinkedIn', 'LinkedIn'), ('Snapchat', 'Snapchat')], max_length=50)),
                ('url_profil', models.URLField()),
                ('nombre_abonnes', models.IntegerField(default=0)),
                ('taux_engagement', models.FloatField(default=0.0)),
                ('moyenne_vues', models.IntegerField(default=0)),
                ('moyenne_likes', models.IntegerField(default=0)),
                ('moyenne_commentaires', models.IntegerField(default=0)),
                ('frequence_publication', models.CharField(choices=[('quotidienne', 'Quotidienne'), ('hebdomadaire', 'Hebdomadaire'), ('bi_hebdomadaire', 'Bi-hebdomadaire'), ('mensuelle', 'Mensuelle')], default='hebdomadaire', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseaux_sociaux', to='users.influencer')),
            ],
            options={
                'verbose_name': 'Réseau Social',
                'verbose_name_plural': 'Réseaux Sociaux',
                'db_table': 'reseaux_sociaux',
                'ordering': ['-nombre_abonnes'],
                'unique_together': {('influencer', 'plateforme')},
            },
        ),
        migrations.CreateModel(
            name='StatistiquesGlobales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers_totaux', models.IntegerField(default=0)),
                ('engagement_moyen_global', models.FloatField(default=0.0)),
                ('croissance_mensuelle', models.FloatField(default=0.0)),
                ('mois', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques_historique', to='users.influencer')),
            ],
            options={
                'verbose_name': 'Statistiques Globales',
                'verbose_name_plural': 'Statistiques Globales',
                'db_table': 'statistiques_globales',
                'ordering': ['-mois'],
                'unique_together': {('influencer', 'mois')},
            },
        ),
    ]
