# Generated by Django 5.2.7 on 2025-10-31 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_completed_profile_influencer_collaboration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.influencer')),
            ],
            options={
                'verbose_name': 'Influencer Image',
                'verbose_name_plural': 'Influencer Images',
                'db_table': 'influencer_images',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfluencerWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('campaign', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=100)),
                ('results', models.TextField(blank=True, null=True)),
                ('publication_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_works', to='users.influencer')),
            ],
            options={
                'verbose_name': 'Influencer Work',
                'verbose_name_plural': 'Influencer Works',
                'db_table': 'influencer_works',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Collaboration',
        ),
    ]
