# Generated by Django 5.2.7 on 2025-10-31 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0003_influencerimage_influencerwork_delete_collaboration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='influencerimage',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'Influencer Image (Deprecated)', 'verbose_name_plural': 'Influencer Images (Deprecated)'},
        ),
        migrations.AlterField(
            model_name='influencerimage',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_images', to='users.influencer'),
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('carousel', 'Carousel'), ('video', 'Video')], max_length=20)),
                ('image_url', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('post_name', models.CharField(max_length=500)),
                ('taken_at', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=255)),
                ('carousel_media', models.JSONField(blank=True, default=list)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_posts', to='users.influencer')),
            ],
            options={
                'verbose_name': 'Instagram Post',
                'verbose_name_plural': 'Instagram Posts',
                'db_table': 'instagram_posts',
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('post_name', models.CharField(max_length=500)),
                ('duration', models.IntegerField()),
                ('taken_at', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=255)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_reels', to='users.influencer')),
            ],
            options={
                'verbose_name': 'Instagram Reel',
                'verbose_name_plural': 'Instagram Reels',
                'db_table': 'instagram_reels',
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'images',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='images_content_d1d020_idx')],
            },
        ),
    ]
