# Generated by Django 5.2.7 on 2025-10-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_influencerimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='instagram_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
