# Generated by Django 5.2.7 on 2025-10-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_influencer_instagram_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='influencerimage',
            name='url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='influencerwork',
            name='publication_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='image_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='thumbnail_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='instagramreel',
            name='thumbnail_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='instagramreel',
            name='video_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='portfoliomedia',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reseausocial',
            name='url_profil',
            field=models.URLField(max_length=500),
        ),
    ]
