# Generated by Django 5.2.7 on 2025-11-06 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_image_url_alter_influencerimage_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('matricule', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('website', models.URLField(blank=True, max_length=1000, null=True)),
                ('size', models.CharField(blank=True, choices=[('S', 'Small (1-50 employees)'), ('M', 'Medium (51-200 employees)'), ('L', 'Large (201-1000 employees)'), ('XL', 'Extra Large (1001+ employees)')], max_length=2, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('domain_activity', models.CharField(blank=True, choices=[('TECH', 'Technology'), ('FIN', 'Finance'), ('HLTH', 'Healthcare'), ('EDU', 'Education'), ('ENT', 'Entertainment'), ('MFG', 'Manufacturing'), ('RET', 'Retail'), ('OTH', 'Other')], max_length=4, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('entreprise_type', models.CharField(blank=True, choices=[('PRIV', 'Private'), ('PUB', 'Public'), ('NGO', 'Non-Governmental Organization'), ('GOV', 'Government Agency')], max_length=4, null=True)),
                ('langues', models.JSONField(blank=True, default=list)),
                ('disponibilite_collaboration', models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé'), ('partiellement_disponible', 'Partiellement disponible')], default='disponible', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='users.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
