# Google App Engine configuration
runtime: python311

# Instance configuration
instance_class: F2

# Automatic scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

# Entry point
entrypoint: gunicorn -b :$PORT brandfluence.wsgi:application --workers 4 --threads 2 --timeout 120

# Environment variables (add your specific values)
env_variables:
  DEBUG: "False"
  # Add DATABASE_URL, SECRET_KEY, and other environment variables here
  # Or use Google Cloud Secret Manager (recommended)

# Handlers for static files
handlers:
  # Static files
  - url: /static
    static_dir: staticfiles/
    secure: always

  # All other routes go to Django app
  - url: /.*
    script: auto
    secure: always
