# Generated by Django 5.2.7 on 2025-12-25 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerapplication',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='offerapplication',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admin', null=True),
        ),
        migrations.AddField(
            model_name='offerapplication',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Optional cover letter from influencer', null=True),
        ),
        migrations.AddField(
            model_name='offerapplication',
            name='delivery_days',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated days to complete', null=True),
        ),
        migrations.AddField(
            model_name='offerapplication',
            name='estimated_reach',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated audience reach', null=True),
        ),
        migrations.AddField(
            model_name='offerapplication',
            name='portfolio_links',
            field=models.JSONField(blank=True, default=list, help_text='Links to previous work'),
        ),
        migrations.AddField(
            model_name='offerapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='offerapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the application was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='offerapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed the application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='offerapplication',
            index=models.Index(fields=['status', '-submitted_at'], name='offer_offer_status_6d46c8_idx'),
        ),
        migrations.AddIndex(
            model_name='offerapplication',
            index=models.Index(fields=['offer', 'status'], name='offer_offer_offer_i_13bc56_idx'),
        ),
    ]
